config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # read toutes les tasks
  get "tasks", to: "tasks#index"

  # create = un get en formulaire (1/2)
  get "tasks/new", to: "tasks#new", as: "new"

  # read une task
  get "tasks/:id", to: "tasks#show", as: "task"

  # create = un post du formulaire (2/2)
  post "tasks", to: "tasks#create"

  # Update une task => un get en formulaire + un post
  get "tasks/:id/edit", to: "tasks#edit", as: "edit"
  patch "tasks/:id", to: "tasks#update"

  # delete
  delete "tasks/:id", to: "tasks#destroy", as: "delete"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)
    redirect_to task_path(@task)
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to taskgs_path, status: :see_other
  end

  private

  def find_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <% if !task.new_record? %>
  <%= f.check_box :completed %>
  <% end %>
  <%= f.submit%>
<% end %>

<p> <%= link_to "Back to the list", tasks_path%> </p>

app/views/tasks/edit.html.erb
<%= render "form", task: @task %>

app/views/tasks/index.html.erb
<div class="text-center" style="width: 50%">

  <ul class="list-unstyled">
    <% @tasks.each do |task|  %>
      <li>

        <div class="d-flex justify-content-between mb-2" >
          <div class="d-flex gap-3">
            <%= link_to task.title, task_path(task)%>
          </div>

          <%# <%= link_to "Delete", delete_path(task), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>

          <%= link_to delete_path(task), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
           <div class="btn btn-warning">
            <%= "Delete" %>
           </div>
          <%end %>

        </div>

      </li>
    <% end%>

  </ul>

  <%= link_to new_path do %>
    <div class="btn btn-primary">
      <%= "Create new task"%>
    </div>
  <% end%>
</div>

app/views/tasks/new.html.erb
<%= render "form", task: @task %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<p> <%= @task.details %> </p>
<% if (@task.completed) %>
  <%= "This task is completed" %>
<%else%>
  <%= "This task is no completed yet" %>
<% end%>

<div class="d-flex gap-3">
<%= link_to "Edit task", edit_path(@task)%>
<%= link_to "Delete task", delete_path(@task), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
</div>
<p> <%= link_to "Back to the list", tasks_path%> </p>